[2021-12-21 19:30:44,833] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T07:00:00+00:00 [queued]>
[2021-12-21 19:30:44,846] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T07:00:00+00:00 [queued]>
[2021-12-21 19:30:44,846] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 19:30:44,846] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-21 19:30:44,846] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 19:30:44,866] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2021-12-21 07:00:00+00:00
[2021-12-21 19:30:44,872] {standard_task_runner.py:52} INFO - Started process 15771 to run task
[2021-12-21 19:30:44,882] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2021-12-21T07:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpnewz01um', '--error-file', '/tmp/tmp3fymyeof']
[2021-12-21 19:30:44,882] {standard_task_runner.py:77} INFO - Job 58: Subtask verificacao_log
[2021-12-21 19:30:44,926] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T07:00:00+00:00 [running]> on host 371b38751bd1
[2021-12-21 19:30:44,976] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2021-12-21T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-21T07:00:00+00:00
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - Data atual:  2021-12-21 19:30:45.420339
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/14 17:10:14
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  7 days, 2:20:31.420326
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/14 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - 
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - 
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - 
[2021-12-21 19:30:45,420] {logging_mixin.py:109} INFO - Erro, tempo entre ultimo log e data atual maior que:  0:10:00
[2021-12-21 19:30:45,420] {python.py:152} INFO - Done. Returned value was: None
[2021-12-21 19:30:45,429] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20211221T070000, start_date=20211221T193044, end_date=20211221T193045
[2021-12-21 19:30:45,452] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 19:30:45,473] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
