[2022-01-11 16:10:00,634] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T16:00:00+00:00 [queued]>
[2022-01-11 16:10:00,641] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T16:00:00+00:00 [queued]>
[2022-01-11 16:10:00,641] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 16:10:00,641] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-11 16:10:00,641] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 16:10:00,649] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): execute_dag> on 2022-01-11 16:00:00+00:00
[2022-01-11 16:10:00,654] {standard_task_runner.py:52} INFO - Started process 3982 to run task
[2022-01-11 16:10:00,656] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'execute_dag', 'scheduled__2022-01-11T16:00:00+00:00', '--job-id', '814', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphpzl2o64', '--error-file', '/tmp/tmp24hih713']
[2022-01-11 16:10:00,656] {standard_task_runner.py:77} INFO - Job 814: Subtask execute_dag
[2022-01-11 16:10:00,683] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.execute_dag scheduled__2022-01-11T16:00:00+00:00 [running]> on host e382db28423e
[2022-01-11 16:10:00,716] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=execute_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T16:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-11T16:00:00+00:00
[2022-01-11 16:10:00,855] {logging_mixin.py:109} INFO - Data atual:  2022-01-11 16:10:00.855232
[2022-01-11 16:10:00,855] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-11 16:10:00,855] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  31 days, 22:59:46.855221
[2022-01-11 16:10:00,855] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-11 16:10:00,855] {logging_mixin.py:109} INFO - 
[2022-01-11 16:10:00,855] {my_dag.py:60} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-11 16:10:00,855] {python.py:152} INFO - Done. Returned value was: None
[2022-01-11 16:10:00,864] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=execute_dag, execution_date=20220111T160000, start_date=20220111T161000, end_date=20220111T161000
[2022-01-11 16:10:00,908] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 16:10:00,932] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
