[2022-01-07 18:36:05,312] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T02:50:00+00:00 [queued]>
[2022-01-07 18:36:05,323] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T02:50:00+00:00 [queued]>
[2022-01-07 18:36:05,323] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:36:05,323] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-07 18:36:05,323] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:36:05,341] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-07 02:50:00+00:00
[2022-01-07 18:36:05,349] {standard_task_runner.py:52} INFO - Started process 732 to run task
[2022-01-07 18:36:05,352] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-07T02:50:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp4hbas65r', '--error-file', '/tmp/tmpcbbr3726']
[2022-01-07 18:36:05,353] {standard_task_runner.py:77} INFO - Job 145: Subtask verificacao_log
[2022-01-07 18:36:05,395] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T02:50:00+00:00 [running]> on host fa901b562f08
[2022-01-07 18:36:05,442] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T02:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-07T02:50:00+00:00
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - Data atual:  2022-01-07 18:36:09.722130
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  28 days, 1:25:55.722121
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:09,722] {logging_mixin.py:109} INFO - Erro, tempo entre ultimo log e data atual maior que:  0:10:00
[2022-01-07 18:36:09,722] {python.py:152} INFO - Done. Returned value was: None
[2022-01-07 18:36:09,736] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220107T025000, start_date=20220107T183605, end_date=20220107T183609
[2022-01-07 18:36:09,777] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-07 18:36:09,813] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
