[2021-12-21 19:37:17,838] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T18:00:00+00:00 [queued]>
[2021-12-21 19:37:17,846] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T18:00:00+00:00 [queued]>
[2021-12-21 19:37:17,846] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 19:37:17,846] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-21 19:37:17,846] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 19:37:17,856] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2021-12-21 18:00:00+00:00
[2021-12-21 19:37:17,860] {standard_task_runner.py:52} INFO - Started process 16188 to run task
[2021-12-21 19:37:17,863] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2021-12-21T18:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpt0nzfkst', '--error-file', '/tmp/tmp8n7dvk3s']
[2021-12-21 19:37:17,863] {standard_task_runner.py:77} INFO - Job 124: Subtask verificacao_log
[2021-12-21 19:37:17,929] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2021-12-21T18:00:00+00:00 [running]> on host 371b38751bd1
[2021-12-21 19:37:17,970] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2021-12-21T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-21T18:00:00+00:00
[2021-12-21 19:37:18,338] {logging_mixin.py:109} INFO - Data atual:  2021-12-21 19:37:18.338881
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/14 17:10:14
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  7 days, 2:27:04.338861
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/14 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - 
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - 
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - 
[2021-12-21 19:37:18,339] {logging_mixin.py:109} INFO - Erro, tempo entre ultimo log e data atual maior que:  0:10:00
[2021-12-21 19:37:18,339] {python.py:152} INFO - Done. Returned value was: None
[2021-12-21 19:37:18,351] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20211221T180000, start_date=20211221T193717, end_date=20211221T193718
[2021-12-21 19:37:18,396] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 19:37:18,455] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-21 19:37:18,471] {dagrun.py:542} INFO - Marking run <DagRun verificacao_log @ 2021-12-21 18:00:00+00:00: scheduled__2021-12-21T18:00:00+00:00, externally triggered: False> successful
[2021-12-21 19:37:18,472] {dagrun.py:602} INFO - DagRun Finished: dag_id=verificacao_log, execution_date=2021-12-21 18:00:00+00:00, run_id=scheduled__2021-12-21T18:00:00+00:00, run_start_date=2021-12-21 19:37:17.067220+00:00, run_end_date=2021-12-21 19:37:18.472288+00:00, run_duration=1.405068, state=success, external_trigger=False, run_type=scheduled, data_interval_start=2021-12-21 18:00:00+00:00, data_interval_end=2021-12-21 18:10:00+00:00, dag_hash=14e79183c98995e94e2cccf25fd08da3
