[2022-01-11 19:35:21,978] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag manual__2022-01-11T19:35:20.901371+00:00 [queued]>
[2022-01-11 19:35:21,986] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.execute_dag manual__2022-01-11T19:35:20.901371+00:00 [queued]>
[2022-01-11 19:35:21,986] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:35:21,986] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-11 19:35:21,987] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 19:35:21,995] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): execute_dag> on 2022-01-11 19:35:20.901371+00:00
[2022-01-11 19:35:21,999] {standard_task_runner.py:52} INFO - Started process 4900 to run task
[2022-01-11 19:35:22,002] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'execute_dag', 'manual__2022-01-11T19:35:20.901371+00:00', '--job-id', '842', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpev8jl1sj', '--error-file', '/tmp/tmpeoatlaz6']
[2022-01-11 19:35:22,003] {standard_task_runner.py:77} INFO - Job 842: Subtask execute_dag
[2022-01-11 19:35:22,044] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.execute_dag manual__2022-01-11T19:35:20.901371+00:00 [running]> on host e382db28423e
[2022-01-11 19:35:22,095] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=iagosilva@mobitbrasil.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=execute_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-01-11T19:35:20.901371+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-11T19:35:20.901371+00:00
[2022-01-11 19:35:22,609] {logging_mixin.py:109} INFO - Data atual:  2022-01-11 19:35:22.609755
[2022-01-11 19:35:22,609] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-11 19:35:22,609] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  32 days, 2:25:08.609741
[2022-01-11 19:35:22,610] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-11 19:35:22,610] {logging_mixin.py:109} INFO - 
[2022-01-11 19:35:22,610] {my_dag.py:83} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-11 19:35:22,610] {python.py:152} INFO - Done. Returned value was: None
[2022-01-11 19:35:22,620] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=execute_dag, execution_date=20220111T193520, start_date=20220111T193521, end_date=20220111T193522
[2022-01-11 19:35:22,657] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-11 19:35:22,683] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
