[2022-01-08 20:59:19,243] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T18:50:00+00:00 [queued]>
[2022-01-08 20:59:19,253] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T18:50:00+00:00 [queued]>
[2022-01-08 20:59:19,254] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-08 20:59:19,254] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-08 20:59:19,254] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-08 20:59:19,266] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-08 18:50:00+00:00
[2022-01-08 20:59:19,270] {standard_task_runner.py:52} INFO - Started process 72862 to run task
[2022-01-08 20:59:19,272] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-08T18:50:00+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpp_lkrthd', '--error-file', '/tmp/tmpx0hq1ps9']
[2022-01-08 20:59:19,272] {standard_task_runner.py:77} INFO - Job 388: Subtask verificacao_log
[2022-01-08 20:59:19,302] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T18:50:00+00:00 [running]> on host fa901b562f08
[2022-01-08 20:59:19,347] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-08T18:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-08T18:50:00+00:00
[2022-01-08 20:59:19,989] {logging_mixin.py:109} INFO - Data atual:  2022-01-08 20:59:19.989728
[2022-01-08 20:59:19,989] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-08 20:59:19,990] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  29 days, 3:49:05.989719
[2022-01-08 20:59:19,990] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-08 20:59:19,990] {logging_mixin.py:109} INFO - 
[2022-01-08 20:59:19,990] {my_dag.py:60} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-08 20:59:19,990] {python.py:152} INFO - Done. Returned value was: None
[2022-01-08 20:59:20,001] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220108T185000, start_date=20220108T205919, end_date=20220108T205920
[2022-01-08 20:59:20,046] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-08 20:59:20,070] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
