[2022-01-07 18:36:42,543] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T08:40:00+00:00 [queued]>
[2022-01-07 18:36:42,554] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T08:40:00+00:00 [queued]>
[2022-01-07 18:36:42,554] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:36:42,554] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-07 18:36:42,554] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-07 18:36:42,567] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-07 08:40:00+00:00
[2022-01-07 18:36:42,572] {standard_task_runner.py:52} INFO - Started process 828 to run task
[2022-01-07 18:36:42,575] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-07T08:40:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp23omvgcj', '--error-file', '/tmp/tmpq1f7iaoz']
[2022-01-07 18:36:42,575] {standard_task_runner.py:77} INFO - Job 180: Subtask verificacao_log
[2022-01-07 18:36:42,605] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-07T08:40:00+00:00 [running]> on host fa901b562f08
[2022-01-07 18:36:42,641] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-07T08:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-07T08:40:00+00:00
[2022-01-07 18:36:47,569] {logging_mixin.py:109} INFO - Data atual:  2022-01-07 18:36:47.569465
[2022-01-07 18:36:47,569] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-07 18:36:47,570] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  28 days, 1:26:33.569423
[2022-01-07 18:36:47,570] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-07 18:36:47,570] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:47,570] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:47,570] {logging_mixin.py:109} INFO - 
[2022-01-07 18:36:47,571] {logging_mixin.py:109} INFO - Erro, tempo entre ultimo log e data atual maior que:  0:10:00
[2022-01-07 18:36:47,571] {python.py:152} INFO - Done. Returned value was: None
[2022-01-07 18:36:47,598] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220107T084000, start_date=20220107T183642, end_date=20220107T183647
[2022-01-07 18:36:47,679] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-07 18:36:47,747] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
