[2022-01-08 20:59:05,076] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T17:50:00+00:00 [queued]>
[2022-01-08 20:59:05,088] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T17:50:00+00:00 [queued]>
[2022-01-08 20:59:05,088] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-08 20:59:05,088] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-08 20:59:05,088] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-08 20:59:05,106] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): verificacao_log> on 2022-01-08 17:50:00+00:00
[2022-01-08 20:59:05,113] {standard_task_runner.py:52} INFO - Started process 72834 to run task
[2022-01-08 20:59:05,137] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'verificacao_log', 'verificacao_log', 'scheduled__2022-01-08T17:50:00+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpejux62sm', '--error-file', '/tmp/tmp4q7aijsl']
[2022-01-08 20:59:05,148] {standard_task_runner.py:77} INFO - Job 378: Subtask verificacao_log
[2022-01-08 20:59:05,229] {logging_mixin.py:109} INFO - Running <TaskInstance: verificacao_log.verificacao_log scheduled__2022-01-08T17:50:00+00:00 [running]> on host fa901b562f08
[2022-01-08 20:59:05,328] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=verificacao_log
AIRFLOW_CTX_TASK_ID=verificacao_log
AIRFLOW_CTX_EXECUTION_DATE=2022-01-08T17:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-08T17:50:00+00:00
[2022-01-08 20:59:06,943] {logging_mixin.py:109} INFO - Data atual:  2022-01-08 20:59:06.943625
[2022-01-08 20:59:06,943] {logging_mixin.py:109} INFO - Dia do ultimo log:  2021/12/10 17:10:14
[2022-01-08 20:59:06,943] {logging_mixin.py:109} INFO - Tempo entre o ultimo log e a data atual:  29 days, 3:48:52.943611
[2022-01-08 20:59:06,943] {logging_mixin.py:109} INFO - INFO   | jvm 4    | 2021/12/10 17:10:14 | [RSFILEMANAGERSERVER] Finalizando importacao lote: DadosSite_03105116_49301_2021121416h55min05seg.zip.rscd. Tempo gasto (ms): 15944
[2022-01-08 20:59:06,944] {logging_mixin.py:109} INFO - 
[2022-01-08 20:59:06,944] {my_dag.py:60} ERROR - tempo entre ultimo log e data atual maior que 10 minutos.
[2022-01-08 20:59:06,944] {python.py:152} INFO - Done. Returned value was: None
[2022-01-08 20:59:06,954] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=verificacao_log, task_id=verificacao_log, execution_date=20220108T175000, start_date=20220108T205905, end_date=20220108T205906
[2022-01-08 20:59:06,989] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-08 20:59:07,011] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
